### ISSUE TITLE
Pin to tiles list (windows 10 - start)

### ISSUE THREAD

**Issue by Hela-Girl** [SyedAounHaiderNaqvi/To-Do_App#11]
The feature of fixing the task list in the Windows startup (in tiles) is very much missing. To display a list of recent tasks in the tile. 
As in the picture below (Yellow square but with to-do list) It's possible to add?

![2022-10-26_10h49_35](https://user-images.githubusercontent.com/20636563/197980404-63fe9f6a-b53a-4098-8a72-0b8efe78aa9d.jpg)

**Comment by SyedAounHaiderNaqvi** [comment]
Hey!
Yes I did have that in the code. But that is outdated as now the app uses dynamic listing. Not sure how I would even implement that, but I will add the tile for pending tasks back (code was there already, must have commented that). I'll let you know when I would even do that, since the app is unstable and I am busy with some college work. Though fret not, I'll add this to my "to-do" hehe.

**Comment by SyedAounHaiderNaqvi** [comment]
By the way, this version you have, did you download it from MS Store?

**Comment by SyedAounHaiderNaqvi** [comment]
Re-introduced this feature with the latest commit, closing this issue.
